---
# tasks file for build-app---
    - name: Install Maven using apt
      apt:
        name: maven
        state: present
      become: yes

    - name: Verify Maven installation
      command: mvn -version
      register: maven_version_output

    - debug:
        msg: "{{ maven_version_output.stdout_lines }}"

    - name: Build the application
      command: ./mvnw clean package
      args:
        chdir: /home/pet-clinic/spring-petclinic
      register: build_result
      ignore_errors: yes


